# Generated by Django 5.2.17 on 2026-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='Special nickname for student authentication', max_length=50, null=True),
        ),
    ]
