# Generated by Django 5.2.17 on 2026-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Student profile image URL (Cloudinary / CDN)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='Optional legacy nickname field', max_length=50, null=True),
        ),
    ]
