# Generated by Django 5.2.17 on 2026-09-16 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, help_text='Weighted total score out of 100', max_digits=6)),
                ('letter_grade', models.CharField(max_length=5)),
                ('passed', models.BooleanField()),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Rank within the course (1 = highest score)', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this result is visible to the student')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='courses.enrollment')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='courses.gradecomponent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.enrollment')),
            ],
            options={
                'ordering': ['component__display_order'],
                'unique_together': {('enrollment', 'component')},
            },
        ),
    ]
